services:
  database:
    image: postgres:15-alpine
    container_name: etl_postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # Mapped to 5433 to avoid conflict with local Postgres instance
      - "5433:5432"
    volumes:
      - postgres_data_storage:/var/lib/postgresql/data

volumes:
  postgres_data_storage: